NavSet's `tagify()` method now returns tagified contents
rstudio/py-shiny pull request #338
Opened 2022-09-28 21:38 UTC by cpsievert

Closes #337

Note that this is needed since `TagList`'s `tagify()` method doesn't recursively call `tagify()` (maybe it should, @wch?)

https://github.com/rstudio/py-htmltools/blob/ae298449b10de5a193031d7c72d7216f7611cf5a/htmltools/_core.py#L172-L194

2022-09-29 17:13 UTC, wch commented
I think that the current behavior for `TagList`'s `tagify()` is correct -- I think it makes sense that if an object's `tagify()` method is called, it is responsible for return a valid tag tree, and this may involve calling `tagify()` on its children. But I'm happy to discuss if something about that doesn't seem right.

2022-09-29 17:35 UTC, cpsievert commented
I can get on board with leaving it as is for the sake of keeping our code simple, but on the other hand, the issue was pretty difficult to debug/identify, and it seems like it could be a very easy/common mistake to make. Also, FWIW, I'm pretty sure `htmltools:::tagify()` doesn't suffer from this same problem (it recurses into the results of `as.tags()`)

2022-09-29 19:19 UTC, wch commented
After thinking about it some more, I'm feel more strongly that the current behavior is correct. If `x` is a `Tag` object, you'd expect to be able to call `x.tagify()` and let that method handle the recursion, instead of having to recurse manually. The same should be true if `x` is a `TagList` -- it would be odd to call `y.tagify()` on each child node and then after that go into each child node and call `z.tagify()` on each of _its_ children.

On a related note, it might make sense for a `TagList` to not have a method named `.tagify()`, but instead `.tagify_children()` (this is related to a discussion with @jcheng5 on Slack).

2022-09-29 22:42 UTC, jcheng5 commented
The reason for not wanting `TagList` to have `tagify`, is because when it _does_ have `tagify`, it means that `TagList` is an instance of `TagChild` (because the `Tagifiable` protocol is one of the union elements of `TagChild`). And as Winston explained it to me, we explicitly do not want `TagList` to be an instance of `TagChild`, as `TagChild` is for representing tag hierarchies post-flattening (not 100% sure about this last part).

2022-09-29 22:59 UTC, jcheng5 commented
If we want to be as strict as @wch is suggesting, I think it's important that `get_html_string` strictly check that it only encounters the exact kinds of objects it expects (`Tag`, `MetadataNode`, and `str`) and throw on anything else.

But also, @wch, it feels like the responsibility to implement recursive `tagify` perfectly is pretty annoying to live up to, no? The type checker doesn't help you because 1) the return type of `tagify` allows `Tagifiable` objects, and 2) you have to remember to make a copy of any `MetadataNode` descendants (if [this comment](https://github.com/rstudio/py-htmltools/blob/ae298449b10de5a193031d7c72d7216f7611cf5a/htmltools/_core.py#L77-L79) is accurate).

2022-09-30 00:26 UTC, wch commented
> But also, @wch, it feels like the responsibility to implement recursive `tagify` perfectly is pretty annoying to live up to, no? The type checker doesn't help you because 1) the return type of `tagify` allows `Tagifiable` objects, and 2) you have to remember to make a copy of any `MetadataNode` descendants (if [this comment](https://github.com/rstudio/py-htmltools/blob/ae298449b10de5a193031d7c72d7216f7611cf5a/htmltools/_core.py#L77-L79) is accurate).

For the sake of argument, let's say that `TagList` has a `tagify_children()` method (instead of `tagify()`). Also keep in mind that each `Tag` object contains a `TagList`, and each `TagList` can contain any number of `Tag` or `Tagifiable` objects. (Set aside the `MetadataNode` and `str` for now.)

So the code looks roughly like this:

```py
class Tag:
    def tagify(self) -> Tag:
        cp = copy(self)
        cp.children = cp.children.tagify()  # Note that cp.children is a TagList
        return cp
       
class TagList(List[Union[Tag, Tagifiable]]):    
    def tagify_children(self) -> TagList:
        cp = copy(self)
        for i in range(len(cp)):
                cp[i] = cp[i].tagify()
        return cp
```

Notice that in `TagList.tagify_children`, it calls `tagify()` on each child, and that's all it needs to do.

If we were to do the thing where we call `tagify()` on a child, and then go into _its_ children and call `tagify()` on them, then that would be kind of weird. In most cases -- when the result of calling `tagify()` on a child is a `Tag`, then we'd end up calling `tagify()` on the grandchildren twice. Basically, if we say that an object's `tagify()` method is sometimes responsible for recursing into its children (as is the case with `Tag`), and sometimes not (as might be the case with `NavSet`), then we're going to end up with a confusing mess.

I wonder if it's possible to get the type system to model the two kinds of trees we're interested in, without going into really awkward contortions:
* One containing `Tag` and `Tagifiable` objects.
* One containing just `Tag` objects. This is what the other kind of tree gets transformed into after `tagify()` is called on it.

We should at the very least have a run time check like the one @jcheng5 suggested for `get_html_string`.

2022-09-30 05:15 UTC, jcheng5 commented
@wch I think you may be thinking of `tagify` differently than @cpsievert and I? Like for you it’s basically a pre-rendering step, whereas to us it’s more like “type conversion to Tag/TagList”.

2022-09-30 16:26 UTC, wch commented
I think we're in agreement that `tagify()` is for type conversion to `Tag`/`TagList`. In practice we use it during pre-rendering, but I wouldn't say that's the only place where it's valid to call it.

2023-06-21 17:00 UTC, schloerke requested changes

2023-06-21 21:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rstudio/py-shiny?pullRequest=338) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rstudio/py-shiny?pullRequest=338) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rstudio/py-shiny?pullRequest=338) it.</sub>

2023-06-23 03:47 UTC, schloerke commented
I don't want to close this PR due to the discussion above. But the PR as be merged in to #580 and will be merged to `main`

2023-06-23 13:52 UTC, cpsievert commented
Seems like we can close #337 then @schloerke?

2023-06-23 13:54 UTC, schloerke commented
> I think we're in agreement that `tagify()` is for type conversion to `Tag`/`TagList`. In practice we use it during pre-rendering, but I wouldn't say that's the only place where it's valid to call it. 

Yes. Sorry I missed this last night.

2023-06-23 14:38 UTC, closed without merging