feat(sidebar): `ui.layout_sidebar()` internally uses `x.ui.layout_sidebar()`
rstudio/py-shiny pull request #568
Opened 2023-06-16 18:50 UTC by schloerke

* `ui.panel_sidebar()` and `ui.panel_main()` return classes so they can have features extracted/altered after init
* Make `sidebar` first arg in `x.ui.page_sidebar()` and `x.ui.layout_sidebar()`
	* Update examples

2023-06-16 19:48 UTC, schloerke commented
** Moving minimal code from experimental to main branch to isolate main from any changes in experimental

2023-06-20 18:30 UTC, wch requested changes

2023-06-20 18:30 UTC, wch commented on shiny/ui/_bootstrap.py
> +    # width: int = 8,
Remove this and documentation for it.

2023-06-20 18:30 UTC, wch commented on shiny/ui/_x/_fill.py
> +fill_container_class = "html-fill-container"
These variables should be all caps.

2023-06-20 20:49 UTC, merged