Use a renderer generator to create sync/async render methods with full typing
rstudio/py-shiny pull request #621
Opened 2023-07-13 20:42 UTC by schloerke

A renderer author can now supply a value that will render a value (`value_fn`) given the result of the user.

Example given `render.text`:

```python
@renderer_gen
def text(
    meta: RenderFunctionMeta,
    value: str | None,
) -> str:
    if value is None:
        return None
    return str(value)
```

<details>
<summary>Previous definition for <code>render.text</code> (w/ docs removed for fair comparison)</summary>

```python
RenderTextFunc = Callable[[], "str | None"]
RenderTextFuncAsync = Callable[[], Awaitable["str | None"]]

class RenderText(RenderFunction["str | None", "str | None"]):
    def __init__(self, fn: RenderTextFunc) -> None:
        super().__init__(fn)
        # The Render*Async subclass will pass in an async function, but it tells the
        # static type checker that it's synchronous. wrap_async() is smart -- if is
        # passed an async function, it will not change it.
        self._fn: RenderTextFuncAsync = _utils.wrap_async(fn)

    def __call__(self) -> str | None:
        return _utils.run_coro_sync(self._run())

    async def _run(self) -> str | None:
        res = await self._fn()
        if res is None:
            return None
        return str(res)

class RenderTextAsync(RenderText, RenderFunctionAsync["str | None", "str | None"]):
    def __init__(self, fn: RenderTextFuncAsync) -> None:
        if not _utils.is_async_callable(fn):
            raise TypeError(self.__class__.__name__ + " requires an async function")
        super().__init__(typing.cast(RenderTextFunc, fn))

    async def __call__(  # pyright: ignore[reportIncompatibleMethodOverride]
        self,
    ) -> str | None:
        return await self._run()

@overload
def text(fn: RenderTextFunc | RenderTextFuncAsync) -> RenderText:
    ...

@overload
def text() -> Callable[[RenderTextFunc | RenderTextFuncAsync], RenderText]:
    ...

def text(
    fn: Optional[RenderTextFunc | RenderTextFuncAsync] = None,
) -> RenderText | Callable[[RenderTextFunc | RenderTextFuncAsync], RenderText]:
    def wrapper(fn: RenderTextFunc | RenderTextFuncAsync) -> RenderText:
        if _utils.is_async_callable(fn):
            return RenderTextAsync(fn)
        else:
            fn = typing.cast(RenderTextFunc, fn)
            return RenderText(fn)

    if fn is None:
        return wrapper
    else:
        return wrapper(fn)
```

</details>

-----------------------------------

Render methods converted: 
- [x] `text`
- [x] `plot`
- [x] `image`
- [x] `table`
- [x] `ui`

TODO:
- [ ] Handle original func name
- [ ] Handle original func docs
- [ ] `self._value_fn()` must handle the `None` case
- [ ] Remove `RenderFunctionMeta`. Just use `RenderFunction`
- [ ] Collapse RenderFunction / RenderSync & RenderFunctionAsync / RenderAsync
- [ ] Be happy with names of classes and types
- [ ] Document `renderer_gen`
- [ ] CHANGELOG entry

Questions
- [ ] In `render.plot()`... Plot variable calls are **after** `self._fn()` has been called. Is this ok? (Previously they were **before**)

----------------------------------

Ex renderer used in testing:

```python
from typing import Optional

from shiny import App, Inputs, Outputs, Session, ui
from shiny.render._render import RenderFunctionMeta, renderer_gen

@renderer_gen
def render_test_text(
    meta: RenderFunctionMeta,
    value: str,
    *,
    extra_txt: Optional[str] = None,
) -> str:
    value = str(value)
    value += "; "
    value += "async" if meta.is_async else "sync"
    if extra_txt:
        value = value + "; " + str(extra_txt)
    return value

app_ui = ui.page_fluid(
    ui.code("t1:"),
    ui.output_text_verbatim("t1"),
    ui.code("t2:"),
    ui.output_text_verbatim("t2"),
    ui.code("t3:"),
    ui.output_text_verbatim("t3"),
    ui.code("t4:"),
    ui.output_text_verbatim("t4"),
    ui.code("t5:"),
    ui.output_text_verbatim("t5"),
    ui.code("t6:"),
    ui.output_text_verbatim("t6"),
)

def server(input: Inputs, output: Outputs, session: Session):
    @output
    @render_test_text
    def t1():
        return "t1; no call"
        # return "hello"

    @output
    @render_test_text
    async def t2():
        return "t2; no call"

    @output
    @render_test_text()
    def t3():
        return "t3; call"

    @output
    @render_test_text()
    async def t4():
        return "t4; call"

    @output
    @render_test_text(extra_txt="w/ extra_txt")
    def t5():
        return "t5; call"

    @output
    @render_test_text(extra_txt="w/ extra_txt")
    async def t6():
        return "t6; call"

app = App(app_ui, server)
```
![Screenshot 2023-07-13 at 4 27 15 PM](https://github.com/rstudio/py-shiny/assets/93231/a54caa36-f536-4a6d-b35a-ffb5c6411f5d)

With expectations:
```python
    OutputTextVerbatim(page, "t1").expect_value("t1; no call; sync")
    OutputTextVerbatim(page, "t2").expect_value("t2; no call; async")
    OutputTextVerbatim(page, "t3").expect_value("t3; call; sync")
    OutputTextVerbatim(page, "t4").expect_value("t4; call; async")
    OutputTextVerbatim(page, "t5").expect_value("t5; call; sync; w/ extra_txt")
    OutputTextVerbatim(page, "t6").expect_value("t6; call; async; w/ extra_txt")
```

2023-08-02 20:01 UTC, wch requested changes

2023-08-02 20:01 UTC, wch commented on shiny/render/_render.py
> +    @property
```suggestion
```

2023-08-02 20:01 UTC, wch commented on shiny/render/_render.py
> +    def __call__(self, *_) -> OT:
Is the `*_` necessary?

2023-08-02 20:01 UTC, wch commented on shiny/render/_render.py
> +        return _utils.run_coro_sync(self._run())
Continue review from here.

2023-08-02 20:02 UTC, wch requested changes
Partial review - will continue later

2023-08-02 20:11 UTC, schloerke commented on shiny/render/_render.py
> +class RenderMeta(NamedTuple):
Not for this situation. We want "immutable" information. The `NamedTuple` is defined from a `Tuple` (immutable) while `TypedDict` and dataclasses are defined using a Dict (mutable).

2023-08-02 20:22 UTC, schloerke commented on shiny/render/_render.py
> +    def __call__(self, *_) -> OT:
No. Removing

2023-08-07 15:28 UTC, wch requested changes

2023-08-10 17:05 UTC, wch approved these changes

2023-08-10 17:05 UTC, wch commented on shiny/api-examples/output_transformer/app.py
> +# See https://www.python.org/dev/peps/pep-0655/#usage-in-python-3-11
```suggestion
```

2023-08-10 19:01 UTC, schloerke commented on shiny/render/_render.py
> +    return str(value)
Using `ValueFn[IT]` type.  Documented when describing `transform_fn` (latest name)

2023-08-10 19:19 UTC, merged